In [2]:
import numpy as np 

In [49]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output


values = np.random.randint(1, 10, size=5)
print(values)

[5 1 6 3 2]


In [52]:
%timeit 1 / big_array

10.1 ms ± 136 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [53]:
big_array = np.random.randint(1, 100, size=1000000)

%timeit compute_reciprocals(big_array)

6.95 s ± 136 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
np.random.seed(1) #고정된 난수 배열
arr1 = np.random.randint(10, size=5)
arr2 = np.random.randint(10, size=5)
print(arr1,arr2)

arr1 = arr1 - 2
print(arr1,arr2)

arr3 = arr1 + arr2
print(arr3)

arr4 = np.random.randint(10, size=(3,5)) 
print(arr4)

arr5 = arr4 ** 2
print(arr5)

[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2] [0 1 7 6 9]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [19]:
#np.abs() 절댓값 계산

x= np.array([-2, -1, 0 ,1, 2])
print(np.abs(x))

x= np.array([3-4j, 4-3j, 2+0j, 0+1j])
print(np.abs(x))

[2 1 0 1 2]
[5. 5. 2. 1.]


In [2]:
# np.linspace(start, stop, num) 
# ex.) x = np.linspace(0, 100, 5) -> 0 25 50 75 100

theta = np.linspace(0, np.pi, 3)

print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

x= np.linspace(0, 100, 11)
print(x)

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [3]:
#reduce 함수

x= np.arange(1,5)
print(x)

aggr = np.add.reduce(x) 
print(aggr) #원소의 합을 나타냄

aggr = np.multiply.reduce(x) #원소의 곱을 나타냄
print(aggr)

[1 2 3 4]
10
24


In [4]:
# accumulate 함수

print(x)

accum = np.add.accumulate(x) # 중간 합의 집계를 보여줌
print(accum)

accum = np.multiply.accumulate(x) # 중간 곱의 집계를 보여줌
print(accum)

[1 2 3 4]
[ 1  3  6 10]
[ 1  2  6 24]


In [38]:
np.random.seed(3)
arr = np.random.rand(100000) # rand() : create 0~1 real number

print(arr)
print("sum =",np.sum(arr))

[0.5507979  0.70814782 0.29090474 ... 0.12599742 0.94189543 0.89025983]
sum = 50103.284993937086


In [41]:
%timeit sum(arr)

7.35 ms ± 285 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [43]:
%timeit np.sum(arr) #1000µs = 1ms numpy가 더 빠르다

40.5 µs ± 1.78 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [48]:
"""
np.sum() 배열 원소 합
np.prod() 배열 원소 곱
np.max() 최댓값
np.min() 최솟값
np.mean() 평균값
np.median() 중앙값
np.percentile() 하위%의 원소
np.std() 표준편차
np.var() 분산
np.argmax() 최댓값 원소 인덱스
np.argmin() 최솟값 원소 인덱스
np.any() 참을 만족하는 원소가 있는지
np.all() 모든 원소들이 참을 만족하는지
"""

print("max =",np.max(arr)) # np.max() 최댓값
print("min =",np.min(arr)) # np.min() 최솟값
print("mean =",np.mean(arr)) # np.mean() 평균값
print("median =",np.median(arr)) #np.median() 중간값
print("percentile =",np.percentile(arr,90)) # np.percentile() 하위%의 원소
                                            # np.percentile(arr,90) arr의 하위90%원소의 값
print(np.any(arr>1)) 
print(np.all(arr>0)) 

max = 0.9999992160832805
min = 1.4735641223229123e-05
mean = 0.5010328499393709
median = 0.5003519408181236
percentile = 0.9017140534612551
False
True


In [2]:
np.random.seed(5)
arr = np.random.randint(10, size = (3,4))
print(arr)

print(np.sum(arr, axis=0)) 
print(np.sum(arr, axis=1))

[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
[12 14 17  8]
[15 28  8]


In [8]:
a = np.ones((3,3)) 
print(a)
b= np.arange(3)
print(b)

print(a+b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [12]:
a = np.arange(3)
print(a)
a = a[:, np.newaxis] # culumn 방향으로 바꾼다
print(a)
b= np.arange(3)
print(b)

print(a+b) # a와 b 3*3행렬로 만든 후 덧셈을 한다

[0 1 2]
[[0]
 [1]
 [2]]
[0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [17]:
a = np.ones((2, 3))
print(a)

b = np.arange(3)
print(b)

print(a+b)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]]


In [3]:
a = np.arange(3)
a = a.reshape((3,1))
print(a)
b = np.arange(3)
print(b)

print(a+b)

[[0]
 [1]
 [2]]
[0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [9]:
x = np.array([1, 2, 3, 4, 5])
print(x)

print(x < 3)
print(x >= 3)
print(x != 3)

[1 2 3 4 5]
[ True  True False False False]
[False False  True  True  True]
[ True  True False  True  True]


In [13]:
np.random.seed(0)

x = np.random.randint(10, size=(3,4)) # 0~9까지의 수 3*4 행렬
print(x)

print(x<6)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[[ True  True  True  True]
 [False False  True  True]
 [ True  True False False]]


In [22]:
# Boolean 의 정수 표현: True: 1, False: 0

print(x)

print(np.count_nonzero(x < 6)) # x < 6 보다 작은 수의 개수(True의 개수)

print(np.sum(x < 6)) # count_nonzero 와 같은 값이 나옴

print(np.any(x > 9))

print(np.all(x > 1))

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
8
8
False
False


In [26]:
#Masking operation

print(x < 5)

print(x[x < 5]) # True의 값들을 배열로 나타내줌

print(np.std(x[x < 5]))

[[False  True  True  True]
 [False False  True False]
 [ True  True False False]]
[0 3 3 3 2 4]
1.2583057392117916


In [37]:
# 팬시 인덱싱 : 한번에 여러 배열 원소에 접근하는 방법

np.random.seed(1)
x = np.random.randint(100, size = 10)
print(x)

print(x[2], x[4], x[6])

ind = [2,4,6]
print(x[ind])

[37 12 72  9 75  5 79 64 16  1]
72 75 79
[72 75 79]


In [58]:
np.random.seed(2)
x = np.random.randint(10, size =(3,5))
print(x)

row = [0, 1, 2]
col = [1, 3, 2]

print(x[row,col])

[[8 8 6 2 8]
 [7 2 1 5 4]
 [4 5 7 3 6]]
[8 5 7]


In [3]:
np.random.seed(0)
x = np.random.randint(10, size = (3,5))
print(x)
row = np.array([0, 1, 2])
col = np.array([2, 1, 4])

print(x[row[:, np.newaxis], col])

[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]]
[[3 0 7]
 [5 3 4]
 [8 6 1]]


In [9]:
x = np.arange(1,13).reshape(3,4)
print(x)

print(x[2, [2, 0, 1]])
print(x[1:, [2, 0, 1]]) # row 1: 1부터 끝까지

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[11  9 10]
[[ 7  5  6]
 [11  9 10]]
