In [12]:
"""
4.2 fuction
"""

"""
Fuctions vs Method
"""

def my_function(x):
    return x + 1
y = 3
my_function(y)

# method : 클래스 내에 정의된 함수

class my_class:
    def my_method(self):
        return x+1
    
cls = my_class()
x=1
print(cls.my_method())


2


In [14]:
"""
Return Keyword
"""

# Leap year : 윤년(2월 29일 까지)

def check_leap_year(year):
    if year % 4 == 0:
        return str(year) + " is a leap year."
    else:
        return str(year) + " is a not leap year."

result = check_leap_year(2021)
print(result)

2021 is a not leap year.


In [7]:
"""
Returning Multiple Values
"""

def square_point(x, y, z):
    x_squared = x ** 2 #x의 2제곱 ** 제곱
    y_squared = y ** 2
    z_squared = z ** 2
    return x_squared,y_squared,z_squared

three_squared,four_squared,five_squared = square_point(3,4,5)
print(three_squared,four_squared,five_squared)

9 16 25


In [46]:
"""
Global Variables
"""

a = "Hello" #전역변수

def prints_a():
    print(a)

prints_a()

Hello


In [8]:
"""
Local Variables
"""

a= 5

def f1():
    a = 2 #지역변수를 우선적으로 참조한다 #지역변수를 함수외부에서 호출하면 에러가 발생함
    print(a)
    
f1()

2


In [1]:
"""
Keywoed Arguments and Default Values
"""

def findvolume(height,width,depth):
    print("Height = " + str(height)) #str() : 어떤 값을 문자열 값으로 변환
    print("width = " + str(width))
    print("depth = " + str(depth))
    return height * width * depth
    

print(findvolume(1,2,3))
print(findvolume(2,1,3))
print(findvolume(width =2, height = 1, depth = 3))

Height = 1
width = 2
depth = 3
6
Height = 2
width = 1
depth = 3
6
Height = 1
width = 2
depth = 3
6


In [3]:
import numpy as np 
import pandas as pd 
from matplotlib import pyplot as plt 

In [6]:
# Creating a Numpy Array
lst = [1, 2, 3, 4]

arr = np.array(lst)
print(lst)

[1, 2, 3, 4]


In [8]:
# dtype attribute

print(arr.dtype) #위에서 선언한 변수 arr의 데이터타입이 int형

int32


In [9]:
"""
Size Comparison of ndarray and list objects
"""

from sys import getsizeof

lst = [1]  
print(getsizeof(lst)) # int(4byte) + object meta info(4byte)

arr = np.array(lst)
print(getsizeof(arr)) #int(4byte)

64
108


In [11]:
"""
Operations with Numpy Arrays
"""

prices = [30, 25, 40, 20, 20, 35, 50, 35]

new_prices = [price -5 for price in prices]
print(new_prices)

prices_arr = np.array(prices)
prices_arr = prices_arr - 5
print(prices_arr)

[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [2]:
"""
실습문제: 시험 점수 처리
"""

test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])


test_3_fixed = test_3 + 2
print(test_3_fixed)

total_grade = test_1 + test_2 + test_3_fixed
print(total_grade)

final_grade = total_grade/3
print(final_grade)

jeremy_test_2 = test_2[3]
print(jeremy_test_2)

manual_adwoa_test_1 = np.array([test_1[1], test_1[2]]) # 결과가 list가 아닌 array 값으로 나타남
print(manual_adwoa_test_1)

student_scores = np.array([test_1, test_2, test_3]) # 배열안에 배열을 넣어 2차원 배열을 표현
print(student_scores)

print(student_scores[2,0]) #가로줄:행(row) 세로줄:열(column)

print(student_scores[:,4]) # :전체를 표현 

[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
93
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87
[87 91 92]


In [13]:
"""
논리연산
"""
a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
mask = a > 5
print(mask)

selected = a[a > 5]
print(selected)

selected = a[(a > 6) | (a < 4)] 
print(selected)

selected = a[(a > 6) & (a < 4)] 
print(selected)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  3  9  8  9  7]
[]


In [6]:
"""
실습문제: 골디락스 포리지(죽) 페스티벌
"""

porridge = np.array([79,65,50,63,56,90,85,98,79,51])

cold = porridge[porridge<60]
print(cold)

hot = porridge[porridge>80]
print(hot)

just_right = porridge[(porridge>60) & (porridge<80)]
print(just_right)

[50 56 51]
[90 85 98]
[79 65 63 79]


In [17]:
"""
Numpy Array Attributes
"""

print(np.arange(3)) #stop 지정값 제외 0,1,2
print(np.arange(3,9)) #start 3 stop 9 
print(np.arange(3,9,2)) #start 3 stop 9 step(간격) 2

[0 1 2]
[3 4 5 6 7 8]
[3 5 7]


In [5]:
"""
Random number
"""

np.random.seed(0) # 난수배열을 지정함
arr1 = np.random.randint(10, size = 6) #(high, size) high = 10(0~9)
print(arr1)

arr2 = np.random.randint(10, size = (3,4)) #3row 4column
print(arr2)

arr3 = np.random.randint(10, size = (3,4,5))
print(arr3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [22]:
print(arr2)

print("arr2.ndim =", arr2.ndim) #차원개수 
print("arr2.shpe =", arr2.shape) # 배열 차원 크기 ex.)size = (3,4)
print("arr2.size =", arr2.size) # 전체 배열 크기(배열 원소 개수)

print("arr2.dtype =", arr2.dtype) # 배열 데이터 타입
print("arr2.itemsize =", arr2.itemsize) # 배열 원소 별 메모리 크기 
print("arr2.nbytes =", arr2.nbytes) # 전체 배열 메모리 크기

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
arr2.ndim = 2
arr2.shpe = (3, 4)
arr2.size = 12
arr2.dtype = int32
arr2.itemsize = 4
arr2.nbytes = 48


In [54]:
"""
Slicing
"""

arr = np.arange(10)
print(arr)

print(arr[3:7])
print(arr[:5]) 
print(arr[5:])
print(arr[::3])
print(arr[2:8:2])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[0 3 6 9]
[2 4 6]


In [34]:
np.random.seed(0)
arr = np.random.randint(10, size = (6,8))
print(arr)

arr_sub = arr[3:5,4:7]
print(arr_sub)

[[5 0 3 3 7 9 3 5]
 [2 4 7 6 8 8 1 6]
 [7 7 8 1 5 9 8 9]
 [4 3 0 3 5 0 2 3]
 [8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7]]
[[5 0 2]
 [3 7 0]]


In [53]:
# .copy()

np.random.seed(0)
arr = np.random.randint(10, size = (3,4))
print(arr, "\n")

arr_sub = arr[:2,:2].copy()
print(arr_sub,"\n")

arr_sub[0,0] = 99
print(arr_sub)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

[[5 0]
 [7 9]] 

[[99  0]
 [ 7  9]]


In [60]:
# arr.reshape() 배열 형상 변경 메소드 

arr = np.arange(1,10)
print(arr,'\n')

#reshape
grid = arr.reshape(3, 3)
print(grid, ' \n')

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]  



In [68]:
# np.newaxis 배열의 추가 차원

arr = np.array([1, 2, 3])
print(arr)
print("arr.ndim = ", arr.ndim)
print("arr.shape = ", arr.shape)

arr_new = arr[:, np.newaxis] #배열 추가
print(arr_new)
print("arr_new.ndim = ", arr_new.ndim)
print("arr_new.shape = ", arr_new.shape)

[1 2 3]
arr.ndim =  1
arr.shape =  (3,)
[[1]
 [2]
 [3]]
arr_new.ndim =  2
arr_new.shape =  (3, 1)


In [85]:
# np.concatenate 배열 연결 메서드

arr_1 = np.array([[1, 2, 3],[1, 2, 3]])
arr_2 = np.array([[4, 5, 6],[4, 5, 6]])
arr_3 = np.array([[7, 8, 9],[7, 8, 9]])

arr_total = np.concatenate([arr_1,arr_2,arr_3], axis = 1) #axis = 0(row 방향) axis = 1(column 방향)
print(arr_total, '\n')

arr_total = np.vstack([arr_1,arr_2,arr_3])
print(arr_total, '\n')

arr_total = np.hstack([arr_1,arr_2,arr_3])
print(arr_total, '\n')

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]] 

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]] 

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]] 



In [69]:
# 배열 분할 메서드 np.split np.vsplit np.hsplit 

arr = [1,2,3,99,99,3,2,1]
print(arr,'\n')

arr_1, arr_2, arr_3 = np.split(arr,[3,5]) # np.split(arr(원본배열),[start:stop])
print(arr_1,arr_2,arr_3)

[1, 2, 3, 99, 99, 3, 2, 1] 

[1 2 3] [99 99] [3 2 1]
